---
version: "3"
services:
 deploy:
   replicas: 2
 devopsdb:
   image: shaikmustafa/myapp:dbimage
   ports:
     - "3306:3306"

 application:
  deploy:
    replicas: 2
   image: shaikmustafa/myapp:appimage
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
